### ISSUE TITLE
Unique file names?

### ISSUE THREAD

**Issue by vvvvvika** [jeremycryan/pytchie#2]
This doesn't have to be anything special, just thought that instead of overwriting any file named "test" is a bit odd. Maybe just add a number at the end?
This is a really cool program with tons of potential.

**Comment by zugzug90** [comment]
@SolarBunny - Hi, nice proposal, as for me.
Here's my [solution](https://github.com/jeremycryan/pytchie/pull/3) which replaces overwrite mode with `new file per each new song` behavior.

/cc @jeremycryan

**Comment by jeremycryan** [comment]
Pytchie now adds sequential numbers each time an output is generated. Thanks @zugzug90 for the PR.
